pool/pool/urls.py
from django.urls import include, re_path as url
from django.contrib import admin

urlpatterns = [
    url(r'^stats/', include('stats.urls')),
    url(r'^admin/', admin.site.urls, name='admin'),
]

pool/stats/urls.py
from django.urls import re_path as url
from django.views.decorators.cache import cache_page
from django.conf import settings

from . import views, status

from .views import division
from .views import feature
from .views import game
from .views import score_sheet
from .views import week
from .views import matchup
from .views import player
from .views import rating
from .views import season
from .views import sponsor
from .views import team
from .views import tournament


view_cache_time = settings.VIEW_CACHE_TIME

urlpatterns = [
    url(r'^$', views.index, name='index'),

    url(r'^feature/$', feature.index, name='feature'),
    url(r'^feature/(?P<feature>[\w]+)/(?P<setting>[\w]+)', feature.save, name='feature_set'),

    url(r'^divisions/(?P<season_id>[0-9]+)', division.divisions, name='divisions'),
    url(r'^divisions/', division.divisions, name='divisions'),

    url(r'^game_update/$', game.update, name='game_update'),

    # the 'after' parameter is really just to make it testable
    url(r'^team/(?P<team_id>[0-9]+)/(?P<after>[0-9-]+)?$', team.team, name='team'),
    url(r'^team/(?P<team_id>[0-9]+)/', team.team, name='team'),
    url(r'^team/register/(?P<team_id>[0-9]+)', team.register, name='register'),
    url(r'^team/register', team.register, name='register'),


    url(r'^teams/(?P<season_id>[0-9]+)', team.teams, name='teams'),
    url(r'^teams/', views.team.teams, name='teams'),

    url(r'^week/(?P<week_id>[0-9]+)/$', week.week, name='week'),
    url(r'^weeks/', week.weeks, name='weeks'),
    url(r'^nextweek/(?P<today_date>[0-9-]+)', week.get_current_week, name='nextweek'),
    url(r'^nextweek/', week.get_current_week, name='nextweek'),

    url(r'^matchup/', matchup.matchup, name='matchup'),

    url(r'^players/(?P<season_id>[0-9]+)', player.players, name='players'),
    url(r'^players/', player.players, name='players'),

    url(r'^player/(?P<player_id>[0-9]+)/(?P<season_id>[0-9]+)/$',
        player.player, name='player'),
    url(r'^player/(?P<player_id>[0-9]+)/$', player.player, name='player'),
    url(r'^player_create/', player.player_create, name='player_create'),

    url(r'^rating/(?P<player_id>[0-9]+)/$', rating.rating, name='rating'),

    url(r'^sponsors/', sponsor.sponsors, name='sponsors'),
    url(r'^sponsor/(?P<sponsor_id>[0-9]+)/$', sponsor.sponsor, name='sponsor'),

    url(r'^score_sheet_create/$', score_sheet.score_sheet_create, name='score_sheet_create'),
    url(r'^score_sheet_copy/$', score_sheet.score_sheet_copy, name='score_sheet_copy'),

    url(r'^score_sheet_lineup/(?P<score_sheet_id>[0-9]+)/(?P<away_home>[a-z]+)$',
        score_sheet.score_sheet_lineup, name='score_sheet_lineup'),
    url(r'^score_sheet_substitutions/(?P<score_sheet_id>[0-9]+)/(?P<away_home>[a-z]+)$',
        score_sheet.score_sheet_substitutions, name='score_sheet_substitutions'),
    url(r'^score_sheet/(?P<score_sheet_id>[0-9]+)/$', score_sheet.score_sheet, name='score_sheet'),
    url(r'^score_sheet/summary/(?P<score_sheet_id>[0-9]+)/$', score_sheet.score_sheet_summary, name='score_sheet_summary'),
    url(r'^score_sheet/comment/', score_sheet.comment, name='score_sheet_comment'),

    url(r'^seasons/', season.seasons, name='seasons'),
    url(r'^set_season/(?P<season_id>[0-9]+)/$', season.set_season, name='set_season'),

    url(r'^tournaments/(?P<season_id>[0-9]+)', cache_page(view_cache_time)(tournament.tournaments), name='tournaments'),
    url(r'^tournaments/', tournament.tournaments, name='tournaments'),
    url(r'^tournament/(?P<tournament_id>[0-9]+)/json', tournament.tournament,  {'json': True}, name='tournament_json'),
    url(r'^tournament/(?P<tournament_id>[0-9]+)', tournament.tournament, name='tournament'),
    url(r'^tournament_edit/(?P<tournament_id>[0-9]+)', tournament.tournament_edit, name='tournament_edit'),
    url(r'^tournament_edit/', tournament.tournament_edit, name='tournament_edit'),
    url(r'^tournament_brackets/(?P<tournament_id>[0-9]+)', tournament.tournament_brackets, name='tournament_brackets'),
    url(r'^tournament_mark_winner/', tournament.tournament_mark_winner, name='tournament_mark_winner'),
    url(r'^tournament_participants/(?P<tournament_id>[0-9]+)', tournament.tournament_participants, name='tournament_participants'),
    url(r'^tournament_controls/(?P<tournament_id>[0-9]+)', tournament.tournament_controls, name='tournament_controls'),


    url(r'^__status', status.index),

]

pool/stats/models/division.py
from django.db import models

from .season import Season


class Division(models.Model):
    season = models.ForeignKey(Season, on_delete=models.CASCADE)
    name = models.CharField(max_length=64)

    def __str__(self):
        return self.name

pool/stats/models/match.py
from django.db import models

from .season import Season
from .table import Table
from .week import Week


class Match(models.Model):
    # the `is_default` season being the default is set in the admin, rather than here,
    # doing it here breaks generating migrations with an empty database.
    season = models.ForeignKey(Season, on_delete=models.CASCADE)
    week = models.ForeignKey(Week, limit_choices_to=models.Q(season__is_default=True), on_delete=models.CASCADE)
    home_team = models.ForeignKey(
        'HomeTeam',
        limit_choices_to=models.Q(season__is_default=True),
        related_name='home_team',
        on_delete=models.CASCADE
    )
    away_team = models.ForeignKey(
        'AwayTeam',
        limit_choices_to=models.Q(season__is_default=True),
        related_name='away_team',
        on_delete=models.CASCADE
    )
    alternate_table = models.ForeignKey(Table, default=None, null=True, blank=True, on_delete=models.CASCADE)
    playoff = models.BooleanField(default=False)

    def __str__(self):
        return "{} @ {}".format(self.away_team, self.home_team)

    def table(self):
        return self.alternate_table if self.alternate_table else self.home_team.table

    class Meta:
        verbose_name = 'Match'
        verbose_name_plural = 'Matches'

pool/stats/models/team.py
import json

from django.db import models
from django.urls import reverse

from .division import Division
from .player import Player
from .scoresheet import ScoreSheet
from .season import Season
from .table import Table


from .globals import away_home, logger


class Team(models.Model):
    # a default season that doesn't bork migrations would be nice
    season = models.ForeignKey(Season, on_delete=models.CASCADE)
    # sponsor = models.ForeignKey(Sponsor, null=True, on_delete=models.CASCADE)
    division = models.ForeignKey(Division, null=True, limit_choices_to=models.Q(
        season__is_default=True), on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    players = models.ManyToManyField(Player, blank=True)
    captain = models.ForeignKey(
        Player, null=True, blank=True, on_delete=models.CASCADE,
        related_name='captain',
    )
    wins = models.IntegerField(verbose_name='Wins', default=0)
    losses = models.IntegerField(verbose_name='Losses', default=0)
    win_percentage = models.FloatField(verbose_name='Win Percentage', default=0.0)
    ranking = models.IntegerField(null=True, blank=True)
    division_ranking = models.IntegerField(null=True, blank=True)
    rank_tie_breaker = models.IntegerField(default=0, null=True, blank=True)
    table = models.ForeignKey(Table, blank=True, null=True, on_delete=models.CASCADE)
    creator_session = models.CharField(max_length=16, null=True, blank=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return "{}".format(self.name)

    def as_dict(self):
        return {
            'name': str(self),
            'url': reverse('team', kwargs={'team_id': self.id}),
        }

    def sponsor(self):
        return self.table.venue

    def adjustments(self):
        a = {
            'wins': 0,
            'losses': 0,
        }
        for adjustment in self.scoreadjustment_set.all():
            a['wins'] += adjustment.wins
            a['losses'] += adjustment.losses
        return a

    def count_games(self):
        """
        Count the summary stats for a team
        :return:
        """
        self.wins = 0
        self.losses = 0
        self.win_percentage = 0.0

        # first, matches involving the team as away team
        away_score_sheets = ScoreSheet.objects.filter(
            match__away_team__exact=self, official__exact=True, match__playoff=False
        )
        for away_score_sheet in away_score_sheets:
            self.wins += len(away_score_sheet.games.filter(winner='away'))
            self.losses += len(away_score_sheet.games.filter(winner='home'))
        home_score_sheets = ScoreSheet.objects.filter(
            match__home_team__exact=self, official__exact=True, match__playoff=False
        )
        for home_score_sheet in home_score_sheets:
            self.wins += len(home_score_sheet.games.filter(winner='home'))
            self.losses += len(home_score_sheet.games.filter(winner='away'))
        if self.losses + self.wins > 0:
            self.win_percentage = self.wins / (self.losses + self.wins)
        adjustments = self.adjustments()
        self.wins += adjustments['wins']
        self.losses += adjustments['losses']
        self.save()

    def forfeit_wins(self):
        forfeit_wins = 0
        for home_away in away_home:
            ss_filter_args = {'match__{}_team'.format(home_away): self}
            home_ss = ScoreSheet.objects.filter(official=1).filter(match__season=self.season).filter(
                **ss_filter_args
            )
            for s in home_ss:
                forfeit_wins += s.forfeit_wins(ah=home_away)
        return forfeit_wins

    def find_score_sheets_against(self, other_teams, official=1):
        return ScoreSheet.objects.filter(
            official=official
        ).filter(
            models.Q(match__away_team__in=other_teams) & models.Q(match__home_team__id=self.id)
            |
            models.Q(match__home_team__in=other_teams) & models.Q(match__away_team__id=self.id)
        )

    def net_game_wins_against(self, tie, score_sheets=None):
        net_wins = 0

        # we need a shallow copy of other_teams here, so we can both call this function as a lambda, and
        # not alter the list in the calling context
        local_other_teams = [x for x in tie.teams.all() if x != self.id]
        if score_sheets is None:  # this is just here to allow passing in score sheets for tests
            score_sheets = self.find_score_sheets_against(local_other_teams)

        # find all the score sheets where this team is home, and one of the others is away, and vice versa
        for score_sheet in score_sheets:
            away_match = 1 if score_sheet.match.away_team == self else -1
            net_wins += score_sheet.away_wins() * away_match - score_sheet.home_wins() * away_match

        return net_wins

    @classmethod
    def update_rankings(cls, season_id):
        Team.update_teams_stats(season_id)
        for division in Division.objects.filter(season_id=season_id).exclude(team__isnull=True):
            Team.rank_teams(Team.objects.filter(division=division), divisional=True)
        Team.rank_teams(Team.objects.filter(season_id=season_id).exclude(division_id=None))

    def get_ranking(self, divisional):
        attribute = 'division_ranking' if divisional else 'ranking'
        return getattr(self, attribute)

    def set_ranking(self, value, divisional):
        attribute = 'division_ranking' if divisional else 'ranking'
        setattr(self, attribute, value)
        self.save()

    @classmethod
    def find_ties(cls, queryset, attribute, divisional=False, set_rankings=False):
        inc = 0
        the_ties = []
        queryset = queryset.order_by('%s%s' % ('-' if attribute == 'win_percentage' else '', attribute))
        while inc < len(queryset):
            offset = 1
            this_tie_teams = [queryset[inc]]
            if inc == (len(queryset) - 1) or \
                    getattr(queryset[inc], attribute) != getattr(queryset[inc + offset], attribute):
                if set_rankings:
                    queryset[inc].set_ranking(inc + 1, divisional)
            while inc + offset < len(queryset) \
                    and getattr(queryset[inc], attribute) == getattr(queryset[inc + offset], attribute):
                this_tie_teams.append(queryset[inc + offset])
                if set_rankings:
                    queryset[inc].set_ranking(inc + 1, divisional)
                    queryset[inc + offset].set_ranking(inc + 1, divisional)
                offset += 1
            if len(this_tie_teams) > 1:
                tie = Tie(
                    season=this_tie_teams[0].season,
                    attribute=attribute,
                )
                tie.save()
                for t in this_tie_teams:
                    tie.teams.add(Team.objects.get(id=t.id))
                tie.save()
                the_ties.append(tie)
            inc += offset
        return the_ties

    @classmethod
    def rank_teams(cls, queryset, divisional=False):

        # we need the team IDs, because we have to re-find the teams to get the updated
        # rankings between tie-breakers
        team_ids = [t.id for t in queryset]

        # clear previous ties, using the first team in the queryset to get the season
        this_season = queryset[0].season
        old_ties = Tie.objects.filter(season=this_season)
        for old_tie in old_ties:
            old_tie.delete()

        # first-order ordering
        the_ties = Team.find_ties(queryset, 'win_percentage', divisional, set_rankings=True)
        # now take the ties, the teams in them are ranked.
        # if a tie can be broken by the net game wins in matches against tied teams,
        # set/save the new ranking, then delete the ties
        for a_tie in the_ties:
            a_tie.break_it('net_game_wins_against', divisional, tie_arg=True, reverse_order=True)

        # there ought to be a way to preserve the ties, but it seems I am going to re-find them
        # to tie-break based on divisional rankings
        if not divisional:
            the_ties = Team.find_ties(Team.objects.filter(id__in=team_ids), 'ranking')
            for a_tie in the_ties:
                a_tie.break_it('division_ranking')

        # OK now, this is the last automatic tie-breaker.
        attribute = 'division_ranking' if divisional else 'ranking'
        the_ties = Team.find_ties(Team.objects.filter(id__in=team_ids), attribute, divisional)
        for a_tie in the_ties:
            a_tie.break_it('forfeit_wins', divisional)

        # norly, the last tie breaker is the rank_tie_breaker, which is populated manually, ie on a coin toss
        the_ties = Team.find_ties(Team.objects.filter(id__in=team_ids), attribute, divisional)
        for a_tie in the_ties:
            a_tie.break_it('rank_tie_breaker', divisional)

    @property
    def score_adjustment(self):

        adjustments = {'wins': 0, 'losses': 0}

        for adjustment in self.scoreadjustment_set.all():
            adjustments['wins'] += adjustment.wins
            adjustments['losses'] += adjustment.losses
        return adjustments

    @classmethod
    def update_teams_stats(cls, season_id):
        teams = cls.objects.filter(season=season_id)
        for this_team in teams:
            this_team.count_games()


class AwayTeam(Team):
    class Meta:
        proxy = True


class HomeTeam(Team):
    class Meta:
        proxy = True


class Tie(models.Model):
    teams = models.ManyToManyField(Team)
    season = models.ForeignKey(Season, on_delete=models.CASCADE)
    attribute = models.CharField(max_length=64)

    def break_it(self, attribute, divisional=False, tie_arg=False, reverse_order=False):
        """

        :param attribute: the attribute or method name we'll use to sort/break this tie
        :param divisional: are we setting divisional rankings? or overall?

pool/stats/models/week.py
from django.db import models

from .season import Season


class Week(models.Model):
    # a default season that doesn't bork migrations would be nice
    season = models.ForeignKey(Season, on_delete=models.CASCADE)
    date = models.DateField(null=True, blank=True)
    name = models.CharField(max_length=32, null=True)

    def __str__(self):
        return "{}".format(self.name)

    @classmethod
    def get_weeks_in_season(cls, before_after, week):
        comp_args = {
            'season_id': week.season,
            'date__{}'.format('lt' if before_after == 'before' else 'gt'): week.date
        }
        weeks = cls.objects.filter(**comp_args).order_by('date')
        if before_after == 'before':
            return list(weeks)[-1] if weeks else None
        else:
            return weeks[0] if weeks else None

    def next(self):
        return self.get_weeks_in_season(before_after='after', week=self)

    def previous(self):
        return self.get_weeks_in_season(before_after='before', week=self)

    def unused_teams(self):
        matches_this_week = self.match_set.all()
        used_teams = set([])
        for m in matches_this_week:
            used_teams.add(m.away_team.id)
            used_teams.add(m.home_team.id)
        return used_teams

    def used_teams(self, team_ids=[]):
        matches_this_week = self.match_set.all()
        used_teams = set([])
        for m in matches_this_week:
            if hasattr(m.away_team, 'id') and m.away_team.id not in team_ids:
                used_teams.add(m.away_team.id)
            if hasattr(m.home_team, 'id') and m.home_team.id not in team_ids:
                used_teams.add(m.home_team.id)
        return used_teams

pool/stats/templates/stats/base.html
<!DOCTYPE html>
{% load static %}
{% load bootstrap %}
<!-- Rev. {{ GIT_BRANCH }} :: {{ GIT_COMMIT }} -->
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% block title%} {% endblock %}</title>
    <!-- Apple Web App -->
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />
    <meta name="description" content="">
    <meta name="author" content="">

    <link href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/css/bootstrap.css" rel="stylesheet">
    <link href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/css/bootstrap-theme.css" rel="stylesheet">
    <link href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.0/bootstrap-table.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'stats/bootstrap-multiselect.css' %}"/>
    <link rel="stylesheet" href="{% static 'stats/custom.css' %}"/>
    <!--<link rel="shortcut icon" href="{{ STATIC_URL }}ico/favicon.ico">-->

    <script src="//code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.0/bootstrap-table.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/d3/5.12.0/d3.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/dagre-d3/0.6.3/dagre-d3.min.js"></script>
    <script src="//cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <script src="{% static 'stats/jquery.confirm.min.js' %}"></script>
    <script src="{% static 'stats/bootstrap-multiselect.js' %}"></script>
    <script src="{% static 'stats/custom.js' %}"></script>
  </head>

<body style="padding-top: 70px;">
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{{ league.url }}">{{ league.name }}</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" style="cursor:pointer">• Seasons</a>
          <ul class="dropdown-menu">
            <li><a href="{% url 'seasons' %}">• All seasons</a></li>
            {% for some_season in seasons %}
            <li><a href="{% url 'set_season' some_season.id%}">{{ some_season }}</a></li>
            {% endfor %}
          </ul>
        </li>
        <!--<li><a href="{% url 'sponsors' %}" data-toggle="collapse" data-target=".navbar-collapse.in">Sponsors</a></li>-->
        <li><a href="{% url 'divisions' %}" class="{% active_page request 'divisions' %}" data-toggle="collapse" data-target=".navbar-collapse.in">Divisions</a></li>
        <li><a href="{% url 'teams' %}" class="{% active_page request 'teams' %}" data-toggle="collapse" data-target=".navbar-collapse.in">Teams</a></li>
        <li><a href="{% url 'players' %}" class="{% active_page request 'players' %}" data-toggle="collapse" data-target=".navbar-collapse.in">Players</a></li>
        <li><a href="{% url 'nextweek' %}">Current Week</a></li>
        <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" style="cursor:pointer">• Weeks</a>
          <ul class="dropdown-menu">
            <li><a href="{% url 'weeks' %}" class="{% active_page request 'weeks' %}" data-toggle="collapse" data-target=".navbar-collapse.in">• All Weeks</a></li>
            {% for season_week in season.week_set.all|dictsort:"date" %}
            <li><a href="{% url 'week' season_week.id%}">{{ season_week }}</a></li>
            {% endfor %}
          </ul>
        </li>
        <li><a href="{% url 'admin:index' %}">Admin</a></li>
      </ul>
    </div>
  </div>
</div>
<div class="container container-main">
  <h5>{{ season }}</h5>
  <div id="content">
  {% block content %}{% endblock %}
  </div>
</div>
<div id="footer">
  <div class="container text-center">
    <hr />
    {% if league.logo %}
    <img src="{{ league.logo }}" />
    {% endif %}
  </div>
</div>
</body>
</html>

pool/stats/templates/stats/match.html
{% extends "stats/base.html" %}

{% block title %}SFPA :: {{ match.season }} :: Week {{ match.week }}{% endblock %}

{% block content %}
{% if match %}
<h1>{{ match.away_team }} @ {{ match.home_team }}</h1>
{% endif %}

{% for games_formset in score_sheets %}
<table class="table table-striped">
{% include "stats/score_sheet_games_form.html" %}
</table>
{% endfor %}

{% endblock %}

pool/stats/templates/stats/seasons.html
{% extends "stats/base.html" %}

{% block content %}

<div class="text-center">
<h2>Seasons</h2>
</div>
{% if seasons %}

<ul>
{% for a_season in seasons %}

<li><h5><a href="{% url 'set_season' a_season.id %}">{{ a_season }}</a></h5></li>

{% endfor %}
</ul>
{% endif %}
{% endblock %}

pool/stats/templates/stats/sponsor.html
{% extends "stats/base.html" %}

{% block title %}SFPA :: Sponsors :: {{ sponsor }}{% endblock %}

{% block content %}
{% if sponsor %}
<h1><a href="{{ sponsor.link }}">{{ sponsor }}</a></h1>
<p>{{ sponsor.address }}</p>
{% endif %}
{% endblock %}

pool/stats/templates/stats/sponsors.html
{% extends "stats/base.html" %}

{% block title %}SFPA :: Sponsors{% endblock %}

{% block content %}

{% if sponsors %}
<ul>
{% for sponsor in sponsors %}
<li><a href="{% url 'sponsor' sponsor.id %}">{{ sponsor }}</a></li>
{% endfor %}
</ul>

{% endif %}
{% endblock %}

pool/stats/templates/stats/team_register.html
{% extends "stats/base.html" %}
{% block title %}SFPA :: Team :: Register {% endblock %}

{% block content %}
{% if registration_open %}
<h2>Register a team</h2>
    <h4>For returning teams/players</h4>
    <p>If you have new players, please contact the <a href="mailto:webmaster.sfpapool@gmail.com">Webmaster</a>. Please provide full legal name, email address, and phone number for each new player.</p>

<form id="team_save" action="{% url 'register'  %}{% if team_id %}/{{ team_id }}{% endif %}" method="post">
    {% if form.non_form_errors %}
        {{ form.non_form_errors }}
    {% endif %}
    {% if form.errors %}
        {{ form.errors }}
    {% endif %}
    <table class="table" style="width: auto;">
    {% csrf_token %}
     <tr>
         <th>{{ form.name.label }}</th><td>{{ form.name }}</td><td>Try to include the sponsor venue's name. Feel free to be punny!</td>
     </tr>
     <tr>
         <th>{{ form.captain.label }}</th><td>{{ form.captain }}</td><td>Required field.</td>
     </tr>
     <tr>
         <th>{{ form.players.label }}</th>
         <td>{{ form.players }}</td>
         <td>
             <ol id="player_names">
                 {% if form.instance.id %}
                     {% for player_name in form.instance.players.all %}
                         <li>{{ player_name }}</li>
                     {% endfor %}
                 {% endif %}
             </ol>
         </td>
     </tr>
     <tr>
         <th>{{ form.table.label }}</th>
         <td>{{ form.table }}</td>
         <td>Don't worry if you aren't 100% sure of the venue and/or table, just leave it blank.</td>
     </tr>
    <tr>
        <td></td>
        <td>
            <input class="btn btn-primary" type="submit" value="Save team" />
        </td>
        <td>Done? Don't forget to save! Then check out the registered <a href="{% url 'teams' season.id %}">teams</a>.</td>
    </tr>
    </table>
</form>
{% else %}
    <h2>Registration is currently closed.</h2>
{% endif %}
<script type="text/javascript">

    $(document).ready(function() {

        let captain_select = $('#id_captain');  // id style is from Django internals
        let player_select = $('#id_players');
        let table_select = $('#id_table');

        function selectCaptainInPlayers() {
            captain_select.find('option:selected').each(function() {
                let captain_id = $(this).val();
                $('#id_players option[value="' + captain_id + '"]').attr('selected', 'selected');
            });
            // since the multi-select plugin creates a UL in front of the HTML select Django
            // builds. you need to update/rebuild it when you change things under the covers.
            player_select.multiselect('rebuild');
        }

        function updatePlayerNamesOL() {
            console.log("updating player names OL");

            let namesOL = $('#player_names');
            let player_names = [];

            player_select.find('option:selected').each(function(){
                console.log("evaluating " + $(this).text());
                if (! player_names.includes($(this).text())) {
                    player_names.push($(this).text());
                }
            });

            namesOL.empty();
            namesOL.append(
              player_names.map(player => $("<li>").text(player)
            ));

        }

        captain_select.prop('required', true).multiselect({
            enableCaseInsensitiveFiltering: true,
            onChange: function() {
                selectCaptainInPlayers();
                updatePlayerNamesOL();
            },
        });
        player_select.multiselect({
            enableCaseInsensitiveFiltering: true,
            numberDisplayed: 1,
            onChange: updatePlayerNamesOL,
        });
        $(table_select).prop('required', false).multiselect({
            enableCaseInsensitiveFiltering: true,
        });
    });

</script>
{% endblock %}

pool/stats/templates/stats/tournament_match_form.html
<form action="{% url 'tournament' tournament_id %}" method="post">
    {% csrf_token %}
    {{ match_form.as_p }}
    <input type="submit" value="Submit" />
</form>